config/routes.rb
Chadz::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {:registrations => "registrations"}  
  
  resources :authentications

  get 'profile/edit' => 'user_infos#edit'

  resources :user_infos, :only => [:index, :edit, :update], :path => 'profile'

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => 'welcome#index'

  post 'messages/:id' => 'messages#destroy'

  put 'messages/:id/:fav' => 'messages#update'

  resources :messages, :only => [:index, :create, :update, :destroy]

  get 'messagebox/customize/' => 'messageboxes#customize'

  post 'messagebox/:process/:messagebox/:user' => 'messageboxes#ban'

  post 'messagebox/settings' => 'messageboxes#settings'

  post 'messagebox/profile' => 'messageboxes#profile'

  post 'messagebox/user/:name' => 'messageboxes#userprofile'
  
  resources :messageboxes, :except => [:new], :path => 'messagebox'

  get "home" => "home#index"

  get 'connections' => "connection#index"

  get 'connections/banned' => "connection#banned"

  get 'connections/:id' => "connection#poster"

  delete 'connections/:id' => "connection#destroy"

  get 'color' => "messageboxes#customize"

  get 'messagebox_attribute' => "messageboxes#customize"

  put 'color.:id' => "messageboxes#savecss"

  put 'messagebox_attribute.:id' => "messageboxes#savecss"
end

app/views/layouts/_leftpart.html.erb
<div class="navbar navbar-inverse ">
	<div class="navbar-inner navbar-fixed-top">
		<div class="container-fluid">
			<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<%= link_to 'Chadz', :root, :class => 'brand' %>
			<div class="container-fluid nav-collapse">
				<ul class="nav pull-right">
					<li <%= 'class=active' if params[:controller] == 'messages' %>>
						<a href="<%= messages_path %>"/><i class="icon-envelope"></i> Messages</a>
					</li>
					<li <%= 'class=active' if params[:controller] == 'messageboxes' %>>
						<a href="<%= messageboxes_path %>"/><i class="icon-list-alt"></i> Messagebox</a>
					</li>
					<li <%= 'class=active' if params[:controller] == 'connection' %>>
						<a href="<%= connections_path %>"/><i class="icon-globe"></i> Connections</a>
					</li>
					<li class="dropdown<%= ' active' if (params[:controller] == 'user_infos' || params[:controller] == 'registrations' || params[:controller] == 'authentications' ) %>">
						<a class="dropdown-toggle" data-toggle="dropdown"  data-target="#" href="#">User</a>
						<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
							<li <%= 'class=active' if params[:controller] == 'user_infos' %>>
								<a href="<%= user_infos_path %>"/><i class="icon-user"></i> Profile</a>
							</li>
							<li <%= 'class=active' if params[:controller] == 'registrations' %>>
								<a href="/users/edit"/><i class="icon-wrench"></i> Account</a>
							</li>
							<li <%= 'class=active' if params[:controller] == 'authentications' %>>
								<a href="<%= authentications_path %>"/><i class="icon-refresh"></i> Authentications</a>
							</li>
							<li class="divider"></li>
							<li><a href="/users/sign_out" data-method="delete" rel="nofollow"><i class="icon-off"></i> Sign out</a></li>
						</ul>
					</li>	
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>
<div id="wrap">
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span9">
				<%= bootstrap_flash %>
				<div class="well">

app/views/layouts/_rightpart.html.erb
        </div>
      </div>
    </div><!--/row-->

  </div> <!-- /container -->
<div class="footer">
  <div class="container">
    <p class="muted credit">designed and developed by @<a href="//www.twitter.com/hudadiaz">hudadiaz</a> | Contact | About</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : (params[:controller]).capitalize+" | Chadz" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%#= stylesheet_link_tag "jquery.cssemoticons" %>
    <%= stylesheet_link_tag params[:controller], :media => "all" %>
    <%= javascript_include_tag "jquery" %>
    <%= javascript_include_tag "jquery_ujs" %>
    <%= javascript_include_tag "bootstrap" %>

  </head>
  <body>
    <%= yield %>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag params[:controller] %>
    <%= javascript_include_tag "application" %>
    <%#= javascript_include_tag "jquery.cssemoticons.min" %>
  </body>
</html>